"""Every country on the map on 1 January 1990: names, government and map colour.

GOV codes: D = parliamentary democracy, C = communist party state, N = authoritarian / monarchy / military rule.
POP overrides the default popularities for that code: (democratic, communism, neutrality, fascism).
COLOR: hand-picked saturated map colours (hex). Tags without one get their vanilla colour, made more vivid.
"""

# tag: (English, Russian, English adjective, Russian adjective, government)
COUNTRIES = {
    # ---- Europe
    "SOV": ("Union of Soviet Socialist Republics", "Союз Советских Социалистических Республик", "Soviet", "советский", "C"),
    "USA": ("United States of America", "Соединённые Штаты Америки", "American", "американский", "D"),
    "ENG": ("United Kingdom", "Великобритания", "British", "британский", "D"),
    "FRA": ("France", "Франция", "French", "французский", "D"),
    "GER": ("West Germany", "ФРГ", "West German", "западногерманский", "D"),
    "DDR": ("East Germany", "ГДР", "East German", "восточногерманский", "C"),
    "ITA": ("Italy", "Италия", "Italian", "итальянский", "D"),
    "SPR": ("Spain", "Испания", "Spanish", "испанский", "D"),
    "POR": ("Portugal", "Португалия", "Portuguese", "португальский", "D"),
    "HOL": ("Netherlands", "Нидерланды", "Dutch", "нидерландский", "D"),
    "BEL": ("Belgium", "Бельгия", "Belgian", "бельгийский", "D"),
    "LUX": ("Luxembourg", "Люксембург", "Luxembourgish", "люксембургский", "D"),
    "SWI": ("Switzerland", "Швейцария", "Swiss", "швейцарский", "D"),
    "AUS": ("Austria", "Австрия", "Austrian", "австрийский", "D"),
    "DEN": ("Denmark", "Дания", "Danish", "датский", "D"),
    "NOR": ("Norway", "Норвегия", "Norwegian", "норвежский", "D"),
    "SWE": ("Sweden", "Швеция", "Swedish", "шведский", "D"),
    "FIN": ("Finland", "Финляндия", "Finnish", "финский", "D"),
    "ICE": ("Iceland", "Исландия", "Icelandic", "исландский", "D"),
    "IRE": ("Ireland", "Ирландия", "Irish", "ирландский", "D"),
    "POL": ("Poland", "Польша", "Polish", "польский", "D"),
    "CZE": ("Czechoslovakia", "Чехословакия", "Czechoslovak", "чехословацкий", "D"),
    "HUN": ("Hungary", "Венгрия", "Hungarian", "венгерский", "D"),
    "ROM": ("Romania", "Румыния", "Romanian", "румынский", "N"),
    "BUL": ("Bulgaria", "Болгария", "Bulgarian", "болгарский", "C"),
    "YUG": ("Yugoslavia", "Югославия", "Yugoslav", "югославский", "C"),
    "ALB": ("Albania", "Албания", "Albanian", "албанский", "C"),
    "GRE": ("Greece", "Греция", "Greek", "греческий", "D"),
    "TUR": ("Turkey", "Турция", "Turkish", "турецкий", "D"),
    "MLT": ("Malta", "Мальта", "Maltese", "мальтийский", "D"),
    "CYP": ("Cyprus", "Кипр", "Cypriot", "кипрский", "D"),
    # ---- Middle East and North Africa
    "ISR": ("Israel", "Израиль", "Israeli", "израильский", "D"),
    "LEB": ("Lebanon", "Ливан", "Lebanese", "ливанский", "N"),
    "SYR": ("Syria", "Сирия", "Syrian", "сирийский", "N"),
    "JOR": ("Jordan", "Иордания", "Jordanian", "иорданский", "N"),
    "IRQ": ("Iraq", "Ирак", "Iraqi", "иракский", "N"),
    "PER": ("Iran", "Иран", "Iranian", "иранский", "N"),
    "KUW": ("Kuwait", "Кувейт", "Kuwaiti", "кувейтский", "N"),
    "SAU": ("Saudi Arabia", "Саудовская Аравия", "Saudi", "саудовский", "N"),
    "BHR": ("Bahrain", "Бахрейн", "Bahraini", "бахрейнский", "N"),
    "QAT": ("Qatar", "Катар", "Qatari", "катарский", "N"),
    "UAE": ("United Arab Emirates", "ОАЭ", "Emirati", "эмиратский", "N"),
    "OMA": ("Oman", "Оман", "Omani", "оманский", "N"),
    "YEM": ("North Yemen", "Северный Йемен", "North Yemeni", "северойеменский", "N"),
    "FSA": ("South Yemen", "Южный Йемен", "South Yemeni", "южнойеменский", "C"),
    "EGY": ("Egypt", "Египет", "Egyptian", "египетский", "N"),
    "LBA": ("Libya", "Ливия", "Libyan", "ливийский", "N"),
    "TUN": ("Tunisia", "Тунис", "Tunisian", "тунисский", "N"),
    "ALG": ("Algeria", "Алжир", "Algerian", "алжирский", "N"),
    "MOR": ("Morocco", "Марокко", "Moroccan", "марокканский", "N"),
    # ---- Sub-Saharan Africa
    "MRT": ("Mauritania", "Мавритания", "Mauritanian", "мавританский", "N"),
    "SEN": ("Senegal", "Сенегал", "Senegalese", "сенегальский", "D"),
    "GAM": ("Gambia", "Гамбия", "Gambian", "гамбийский", "D"),
    "GNB": ("Guinea-Bissau", "Гвинея-Бисау", "Bissau-Guinean", "гвинейский", "N"),
    "GNA": ("Guinea", "Гвинея", "Guinean", "гвинейский", "N"),
    "SIE": ("Sierra Leone", "Сьерра-Леоне", "Sierra Leonean", "сьерра-леонский", "N"),
    "LIB": ("Liberia", "Либерия", "Liberian", "либерийский", "N"),
    "IVO": ("Côte d'Ivoire", "Кот-д'Ивуар", "Ivorian", "ивуарийский", "N"),
    "VOL": ("Burkina Faso", "Буркина-Фасо", "Burkinabé", "буркинийский", "N"),
    "MLI": ("Mali", "Мали", "Malian", "малийский", "N"),
    "NGR": ("Niger", "Нигер", "Nigerien", "нигерский", "N"),
    "GHA": ("Ghana", "Гана", "Ghanaian", "ганский", "N"),
    "TOG": ("Togo", "Того", "Togolese", "тоголезский", "N"),
    "DAH": ("Benin", "Бенин", "Beninese", "бенинский", "N"),
    "NGA": ("Nigeria", "Нигерия", "Nigerian", "нигерийский", "N"),
    "CMR": ("Cameroon", "Камерун", "Cameroonian", "камерунский", "N"),
    "CHA": ("Chad", "Чад", "Chadian", "чадский", "N"),
    "CAR": ("Central African Republic", "ЦАР", "Central African", "центральноафриканский", "N"),
    "EQG": ("Equatorial Guinea", "Экваториальная Гвинея", "Equatoguinean", "экваториальногвинейский", "N"),
    "GAB": ("Gabon", "Габон", "Gabonese", "габонский", "N"),
    "RCG": ("Congo", "Конго", "Congolese", "конголезский", "C"),
    "COG": ("Zaire", "Заир", "Zairean", "заирский", "N"),
    "ANG": ("Angola", "Ангола", "Angolan", "ангольский", "C"),
    "ZAM": ("Zambia", "Замбия", "Zambian", "замбийский", "N"),
    "MLW": ("Malawi", "Малави", "Malawian", "малавийский", "N"),
    "MZB": ("Mozambique", "Мозамбик", "Mozambican", "мозамбикский", "C"),
    "ZIM": ("Zimbabwe", "Зимбабве", "Zimbabwean", "зимбабвийский", "N"),
    "BOT": ("Botswana", "Ботсвана", "Botswanan", "ботсванский", "D"),
    "SAF": ("South Africa", "ЮАР", "South African", "южноафриканский", "N"),
    "TZN": ("Tanzania", "Танзания", "Tanzanian", "танзанийский", "N"),
    "KEN": ("Kenya", "Кения", "Kenyan", "кенийский", "N"),
    "UGA": ("Uganda", "Уганда", "Ugandan", "угандийский", "N"),
    "RWA": ("Rwanda", "Руанда", "Rwandan", "руандийский", "N"),
    "BRD": ("Burundi", "Бурунди", "Burundian", "бурундийский", "N"),
    "SUD": ("Sudan", "Судан", "Sudanese", "суданский", "N"),
    "ETH": ("Ethiopia", "Эфиопия", "Ethiopian", "эфиопский", "C"),
    "SOM": ("Somalia", "Сомали", "Somali", "сомалийский", "N"),
    "DJI": ("Djibouti", "Джибути", "Djiboutian", "джибутийский", "N"),
    "MAD": ("Madagascar", "Мадагаскар", "Malagasy", "малагасийский", "N"),
    "MRI": ("Mauritius", "Маврикий", "Mauritian", "маврикийский", "D"),
    "SEY": ("Seychelles", "Сейшельские Острова", "Seychellois", "сейшельский", "N"),
    "COM": ("Comoros", "Коморские Острова", "Comorian", "коморский", "N"),
    "STP": ("São Tomé and Príncipe", "Сан-Томе и Принсипи", "Santomean", "сан-томийский", "C"),
    "CBV": ("Cape Verde", "Кабо-Верде", "Cape Verdean", "кабовердианский", "N"),
    # ---- Asia
    "AFG": ("Afghanistan", "Афганистан", "Afghan", "афганский", "C"),
    "PAK": ("Pakistan", "Пакистан", "Pakistani", "пакистанский", "D"),
    "RAJ": ("India", "Индия", "Indian", "индийский", "D"),
    "BAN": ("Bangladesh", "Бангладеш", "Bangladeshi", "бангладешский", "N"),
    "SRL": ("Sri Lanka", "Шри-Ланка", "Sri Lankan", "шри-ланкийский", "D"),
    "MLD": ("Maldives", "Мальдивы", "Maldivian", "мальдивский", "N"),
    "NEP": ("Nepal", "Непал", "Nepali", "непальский", "N"),
    "BHU": ("Bhutan", "Бутан", "Bhutanese", "бутанский", "N"),
    "BRM": ("Burma", "Бирма", "Burmese", "бирманский", "N"),
    "SIA": ("Thailand", "Таиланд", "Thai", "тайский", "D"),
    "LAO": ("Laos", "Лаос", "Lao", "лаосский", "C"),
    "CAM": ("Cambodia", "Камбоджа", "Cambodian", "камбоджийский", "C"),
    "VIN": ("Vietnam", "Вьетнам", "Vietnamese", "вьетнамский", "C"),
    "MAL": ("Malaysia", "Малайзия", "Malaysian", "малайзийский", "D"),
    "SNG": ("Singapore", "Сингапур", "Singaporean", "сингапурский", "D"),
    "BRN": ("Brunei", "Бруней", "Bruneian", "брунейский", "N"),
    "INS": ("Indonesia", "Индонезия", "Indonesian", "индонезийский", "N"),
    "PHI": ("Philippines", "Филиппины", "Filipino", "филиппинский", "D"),
    "PRC": ("China", "Китай", "Chinese", "китайский", "C"),
    "CHI": ("Taiwan", "Тайвань", "Taiwanese", "тайваньский", "N"),
    "MON": ("Mongolia", "Монголия", "Mongolian", "монгольский", "C"),
    "PRK": ("North Korea", "КНДР", "North Korean", "северокорейский", "C"),
    "KOR": ("South Korea", "Южная Корея", "South Korean", "южнокорейский", "D"),
    "JAP": ("Japan", "Япония", "Japanese", "японский", "D"),
    # ---- Oceania
    "AST": ("Australia", "Австралия", "Australian", "австралийский", "D"),
    "NZL": ("New Zealand", "Новая Зеландия", "New Zealand", "новозеландский", "D"),
    "PNG": ("Papua New Guinea", "Папуа — Новая Гвинея", "Papua New Guinean", "папуасский", "D"),
    "SOL": ("Solomon Islands", "Соломоновы Острова", "Solomon Islander", "соломонский", "D"),
    "VAN": ("Vanuatu", "Вануату", "Ni-Vanuatu", "вануатский", "D"),
    "FIJ": ("Fiji", "Фиджи", "Fijian", "фиджийский", "N"),
    "SAM": ("Western Samoa", "Западное Самоа", "Samoan", "самоанский", "D"),
    "KIR": ("Kiribati", "Кирибати", "I-Kiribati", "кирибатийский", "D"),
    "TUV": ("Tuvalu", "Тувалу", "Tuvaluan", "тувалуанский", "D"),
    "NRU": ("Nauru", "Науру", "Nauruan", "науруанский", "D"),
    # ---- Americas
    "CAN": ("Canada", "Канада", "Canadian", "канадский", "D"),
    "MEX": ("Mexico", "Мексика", "Mexican", "мексиканский", "N"),
    "GUA": ("Guatemala", "Гватемала", "Guatemalan", "гватемальский", "D"),
    "BLZ": ("Belize", "Белиз", "Belizean", "белизский", "D"),
    "HON": ("Honduras", "Гондурас", "Honduran", "гондурасский", "D"),
    "ELS": ("El Salvador", "Сальвадор", "Salvadoran", "сальвадорский", "D"),
    "NIC": ("Nicaragua", "Никарагуа", "Nicaraguan", "никарагуанский", "C"),
    "COS": ("Costa Rica", "Коста-Рика", "Costa Rican", "костариканский", "D"),
    "PAN": ("Panama", "Панама", "Panamanian", "панамский", "D"),
    "CUB": ("Cuba", "Куба", "Cuban", "кубинский", "C"),
    "JAM": ("Jamaica", "Ямайка", "Jamaican", "ямайский", "D"),
    "HAI": ("Haiti", "Гаити", "Haitian", "гаитянский", "N"),
    "DOM": ("Dominican Republic", "Доминиканская Республика", "Dominican", "доминиканский", "D"),
    "BAH": ("Bahamas", "Багамские Острова", "Bahamian", "багамский", "D"),
    "TRI": ("Trinidad and Tobago", "Тринидад и Тобаго", "Trinidadian", "тринидадский", "D"),
    "BRB": ("Barbados", "Барбадос", "Barbadian", "барбадосский", "D"),
    "BAS": ("Antigua and Barbuda", "Антигуа и Барбуда", "Antiguan", "антигуанский", "D"),
    "GYA": ("Guyana", "Гайана", "Guyanese", "гайанский", "N"),
    "SUR": ("Suriname", "Суринам", "Surinamese", "суринамский", "D"),
    "VEN": ("Venezuela", "Венесуэла", "Venezuelan", "венесуэльский", "D"),
    "COL": ("Colombia", "Колумбия", "Colombian", "колумбийский", "D"),
    "ECU": ("Ecuador", "Эквадор", "Ecuadorian", "эквадорский", "D"),
    "PRU": ("Peru", "Перу", "Peruvian", "перуанский", "D"),
    "BOL": ("Bolivia", "Боливия", "Bolivian", "боливийский", "D"),
    "PAR": ("Paraguay", "Парагвай", "Paraguayan", "парагвайский", "N"),
    "CHL": ("Chile", "Чили", "Chilean", "чилийский", "N"),
    "ARG": ("Argentina", "Аргентина", "Argentine", "аргентинский", "D"),
    "URG": ("Uruguay", "Уругвай", "Uruguayan", "уругвайский", "D"),
    "BRA": ("Brazil", "Бразилия", "Brazilian", "бразильский", "D"),
}

# default popularities per government code: democratic, communism, neutrality, fascism
GOV_POP = {"D": (78, 6, 13, 3), "C": (8, 82, 8, 2), "N": (14, 8, 74, 4)}

POP = {
    "SOV": (20, 72, 6, 2), "USA": (96, 1, 2, 1),
    "DDR": (35, 55, 8, 2), "CZE": (50, 38, 10, 2), "POL": (55, 35, 8, 2), "HUN": (60, 30, 8, 2),
    "ROM": (25, 25, 48, 2), "BUL": (25, 65, 8, 2), "YUG": (20, 60, 15, 5), "ALB": (3, 92, 4, 1),
    "ITA": (65, 27, 5, 3), "FRA": (80, 10, 6, 4), "GRE": (75, 18, 5, 2), "POR": (82, 12, 5, 1),
    "SPR": (85, 9, 4, 2), "TUR": (70, 4, 22, 4), "ISR": (88, 2, 8, 2),
    "PRC": (5, 85, 10, 0), "CHI": (40, 0, 58, 2), "KOR": (62, 2, 34, 2), "PRK": (0, 98, 2, 0),
    "NIC": (40, 50, 9, 1), "AFG": (5, 45, 50, 0), "ETH": (5, 60, 35, 0), "ANG": (8, 70, 22, 0),
    "MZB": (8, 70, 22, 0), "RCG": (15, 60, 25, 0), "FSA": (10, 70, 20, 0), "CAM": (5, 70, 25, 0),
    "CHL": (40, 10, 48, 2), "PAR": (30, 2, 66, 2), "MEX": (25, 5, 68, 2), "SAF": (35, 5, 50, 10),
    "IRQ": (2, 5, 90, 3), "SYR": (2, 6, 90, 2), "LBA": (2, 8, 88, 2), "PER": (5, 3, 90, 2),
    "PAK": (60, 5, 32, 3), "RAJ": (85, 8, 6, 1), "PHI": (70, 8, 20, 2),
}

COLOR = {
    "SOV": "c41f24", "USA": "2f6fd6", "ENG": "c8325a", "FRA": "2b5fd0", "GER": "7d8c99", "DDR": "e0682a",
    "ITA": "3aa34a", "SPR": "e3b52b", "POR": "2a9d6a", "HOL": "f07d1f", "BEL": "e0c22c", "LUX": "4fb3c9",
    "SWI": "d93030", "AUS": "d2d2d2", "DEN": "c94545", "NOR": "8d4ab8", "SWE": "2f8fd6", "FIN": "eaeaea",
    "ICE": "6aa6e0", "IRE": "2fb35a", "POL": "d9437c", "CZE": "3f7fd9", "HUN": "b8742e", "ROM": "e8c62c",
    "BUL": "3fae4f", "YUG": "3c5ad1", "ALB": "c23a2a", "GRE": "5aa4ea", "TUR": "c06a35", "CYP": "e09a3a",
    "PRC": "e8552a", "CHI": "2f5fc0", "MON": "a8304f", "PRK": "b5283a", "KOR": "4a8ad6", "JAP": "eadcb4",
    "RAJ": "e88a2a", "PAK": "2f9a4a", "PER": "3ab08e", "IRQ": "c4a46a", "SAU": "4f9e2e", "EGY": "dcc25a",
    "CAN": "b8406e", "MEX": "4fa84f", "BRA": "3fb04a", "ARG": "7abaea", "AST": "3fa884", "CUB": "2f6ad0",
    "VIN": "dcb02a", "INS": "c94a4a", "AFG": "a87a4a",
}
