l_russian:
 TOTU_FE_SETTINGS_TAB_GAME:0 "Игра"
 TOTU_FE_SETTINGS_TAB_VIDEO:0 "Графика"
 TOTU_FE_SETTINGS_TAB_AUDIO:0 "Звук"
 TOTU_FE_SETTINGS_TAB_CONTROLS:0 "Управление"
 TOTU_FE_SETTINGS_APPLY:0 "Применить"
 TOTU_FE_SETTINGS_MUSIC_PLAYER:0 "Музыкальный плеер"
