l_english:
 TOTU_FE_SETTINGS_TAB_GAME:0 "Game"
 TOTU_FE_SETTINGS_TAB_VIDEO:0 "Video"
 TOTU_FE_SETTINGS_TAB_AUDIO:0 "Audio"
 TOTU_FE_SETTINGS_TAB_CONTROLS:0 "Controls"
 TOTU_FE_SETTINGS_APPLY:0 "Apply"
 TOTU_FE_SETTINGS_MUSIC_PLAYER:0 "Music player"
