"""Area 'popups': the popup-local textures of popupwindow.gui / notifications (broadcast style).

Window paintings become the flat in-game board (BOARD at 0.90, the GFX_totu_board_ig tone), so any view that
still draws them reads as one board. Overlay art (header art, bottom strips, frames, corner ornaments, laurel,
agency smoke) becomes transparent: the window's own board shows through. The notification timeout bar is a
P fill over a D 18 % track. Pixel sizes stay vanilla. interface/popupwindow.gui itself is generated by
tools/build_popups_gfx.py (it already hides the overlays and draws GFX_totu_board_ig).
"""

AREA = "popups"


def board(ctx, src):
    """full-window painting -> flat board at the in-game alpha"""
    return ctx.flat(ctx.BOARD, ctx.BOARD_ALPHA)


def clear(ctx, src):
    """decorative overlay -> fully transparent"""
    return ctx.blank()


def bar_fill(ctx, src):
    return ctx.flat(ctx.P, 1.0)


def bar_track(ctx, src):
    return ctx.flat(ctx.D, ctx.TRACK_ALPHA)


TEXTURES = {
    # window backgrounds (political goal / release country, capitulation, exile hosted)
    "pol_goal_popup_bg.dds": board,
    "capitulation_bg.dds": board,
    "new_exile_hosted_bg.dds": board,
    "new_exile_hosted_small_bg.dds": board,
    # overlays: header art, bottom strips (settings.gui's tab strip too), laurel, smoke, frames, ornaments
    "diplo_popup_header_bg.dds": clear,
    "diplo_popup_header_bg_large.dds": clear,
    "diplo_popup_bottom.dds": clear,
    "diplo_popup_bottom_large.dds": clear,
    "focus_popup_bg.dds": clear,
    "operatives/intelligence_agency_popup_bg.dds": clear,
    "peace_conference/pc_decoration_top_left.dds": clear,
    "peace_conference/pc_decoration_top_right.dds": clear,
    "leader_frame_0_6.dds": clear,
    # notification timeout bar (GFX_popup_progressbar)
    "deployment_entry_progressbar.dds": bar_fill,
    "deployment_entry_progressbar_bg.dds": bar_track,
}

LOSSLESS = {"deployment_entry_progressbar.dds", "deployment_entry_progressbar_bg.dds"}
