"""tools/build_misc_gfx.py: sprites of the area 'misc' (credits, music player, achievements, subscription overlay).

Writes gfx/interface/totu/misc/*.dds and interface/totu_misc.gfx, plus tools/preview/misc_sprites.png.

    GFX_totu_misc_credits_scrim   500x560   column scrim behind the credits roll (black, soft left/right/top/bottom)
    GFX_totu_misc_track_row       536x30    keyer row of the music player's current track (music_track_entry)

Everything else in these windows comes from the kit (boards, plates, close, scrollbars). Vanilla textures owned by
'misc' are flattened by tools/ingame/misc.py (build_ingame_gfx.py --only misc).
"""
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
import totu_broadcast as tb  # noqa: E402

AREA = "misc"
OUT = tb.TOTU_TEX / AREA
GFX = tb.INTERFACE / f"totu_{AREA}.gfx"
TEX = f"gfx/interface/totu/{AREA}"

CREDITS_W, CREDITS_H = 500, 560      # vanilla frontendcreditsview column (kept: the engine scrolls inside it)
SCRIM_A = 0.60                       # plateau alpha of the column scrim
ROW_W, ROW_H = 536, 30               # music_track_entry in the restyled musicplayer.gui


def smooth(t):
    t = np.clip(t, 0.0, 1.0)
    return t * t * (3 - 2 * t)


def credits_scrim():
    """Black column, no visible edge on the menu photo: a plateau over the middle 54 % of the width (the
    names' measure), a smoothstep to 0 at the left/right edges, and 120 px fades at the top and bottom."""
    w, h = CREDITS_W, CREDITS_H
    xx = (np.arange(w, dtype=np.float32) + 0.5) / w
    yy = np.arange(h, dtype=np.float32) + 0.5
    hx = 1 - smooth((np.abs(xx - 0.5) - 0.27) / 0.23)
    vy = smooth(yy / 120.0) * smooth((h - yy) / 120.0)
    alpha = SCRIM_A * vy[:, None] * hx[None, :]
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    img.putalpha(Image.fromarray(np.round(alpha * 255).astype(np.uint8)))
    return img


def track_row():
    return tb.flat(ROW_W, ROW_H, tb.KEY_BLUE, 1.0)


def main():
    scrim = credits_scrim()
    row = track_row()
    blocks = [
        tb.sprite_block("GFX_totu_misc_credits_scrim", f"{TEX}/credits_scrim.dds",
                        comment="credits roll: column scrim (frontendcreditview.gui background)"),
        tb.sprite_block("GFX_totu_misc_track_row", f"{TEX}/track_row.dds",
                        comment="music player: current track row, keyer at 100 % (musicplayer.gui current_track)"),
    ]
    text = tb.gfx_file(blocks, ["Twilight of the Union: misc sprites (credits, music player, achievements).",
                                "Generated by tools/build_misc_gfx.py; do not edit by hand."])
    # check first, write after
    names = tb.declared_names(text)
    assert len(names) == len(set(names)), names
    clash = {n: v for n, v in tb.existing_names("*.gfx", exclude=[GFX]).items() if n in names}
    assert not clash, clash
    tb.save_dds(scrim, OUT / "credits_scrim.dds", fmt=tb.dds_policy(*scrim.size))
    tb.save_dds(row, OUT / "track_row.dds")
    tb.write_text(GFX, text)
    tb.assert_declared(GFX, names)
    tb.contact_sheet([
        "misc sprites",
        ("credits_scrim 500x560 (over the board preview)", tb.over(tb.preview_bg(*scrim.size, alpha=0.0), scrim, (0, 0))),
        ("track_row 536x30", row),
    ], tb.PREVIEW / f"{AREA}_sprites.png", bg="checker")


if __name__ == "__main__":
    main()
