"""Writes common/bookmarks/totu_1990.txt.

The scenario window only appears when there are at least two bookmarks, so the file holds the
real 1990 bookmark plus a hidden clone (same content, no `default = yes`). The scenario window
clips its grid to one slot (interface/frontendgamesetupview.gui, "bookmarks"), so only one shows.
Generating both from one list keeps them identical.

Usage: python tools/build_bookmarks.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Order matters: majors fill the top row left to right (USA left banner, SOV right banner).
MAJORS = [
    ("USA", "democratic"),
    ("SOV", "communism"),
]
# National spirits shown in the country selection "ideas" box (about three fit).
SHOWN_IDEAS = {
    "SOV": ["TOTU_SOV_no_plan_no_market", "TOTU_SOV_glasnost", "TOTU_SOV_awakening_republics"],
}
# Minor flags row, 8 slots. Their history files are generated stubs (tools/build_map.py).
MINORS = [
    ("POL", "democratic"),
    ("CZE", "democratic"),
    ("HUN", "democratic"),
    ("ROM", "neutrality"),
    ("BUL", "communism"),
    ("PRC", "communism"),
    ("ENG", "democratic"),
    ("FRA", "democratic"),
]


def bookmark(default):
    lines = [
        "\tbookmark = {",
        '\t\tname = "TOTU_1990_NAME"',
        '\t\tdesc = "TOTU_1990_DESC"',
        "\t\tdate = 1990.1.1.12",
        '\t\tpicture = "GFX_select_date_1990"',
        '\t\tdefault_country = "SOV"',
    ]
    if default:
        lines.append("\t\tdefault = yes")
    lines.append("")
    for tag, ideology in MAJORS:
        lines += [f'\t\t"{tag}" = {{', f'\t\t\thistory = "TOTU_{tag}_1990_DESC"', f"\t\t\tideology = {ideology}"]
        if tag in SHOWN_IDEAS:
            lines += ["\t\t\tideas = {"] + [f"\t\t\t\t{idea}" for idea in SHOWN_IDEAS[tag]] + ["\t\t\t}"]
        lines += ["\t\t}", ""]
    for tag, ideology in MINORS:
        lines += [f'\t\t"{tag}" = {{', "\t\t\tminor = yes", f'\t\t\thistory = "TOTU_{tag}_1990_DESC"',
                  f"\t\t\tideology = {ideology}", "\t\t}", ""]
    # No "---" (other countries) entry: the engine puts it in the majors row, which is designed
    # for exactly two cards. Any other country can still be picked by clicking it on the map.
    lines += [
        "\t\teffect = {",
        "\t\t\trandomize_weather = 22345 # vanilla: obligatory in every bookmark",
        "\t\t}",
        "\t}",
    ]
    return "\n".join(lines)


def main():
    text = "\n".join([
        "# GENERATED by tools/build_bookmarks.py - edit the script, not this file.",
        "# Real 1990 bookmark + hidden clone; see the script docstring for why.",
        "",
        "bookmarks = {",
        bookmark(default=True),
        "",
        "\t# Hidden clone",
        bookmark(default=False),
        "}",
        "",
    ])
    out = ROOT / "common/bookmarks/totu_1990.txt"
    out.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", out.relative_to(ROOT))


if __name__ == "__main__":
    main()
